import { useEffect, useMemo, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Activity, FileStack, Loader2, RefreshCw, Search, ShieldCheck, Users } from 'lucide-react';
import { User } from '@supabase/supabase-js';
import { supabase } from '../lib/supabase';

interface Props { user: User | null; loading: boolean; }
type Overview={statistics:{totalUsers:number;totalDocuments:number;verifiedPackages:number;pendingPackages:number;failedVerifications:number};activity:Event[]}; type Event={id:string;description:string;actor:string;createdAt:string}; type AdminUser={id:string;email:string;name:string;role:string;createdAt:string}; type Pkg={id:string;title:string;sender:string;status:string;expiresAt:string;downloadCount:number;fileCount:number;verificationStatus:string;createdAt:string}; type Verification={id:string;document:string;sender:string;method:string;status:string;result:string;createdAt:string}; type Audit={id:string;user:string;action:string;resource:string;status:string;createdAt:string};
const links=[['/admin','Overview'],['/admin/users','Users'],['/admin/documents','Documents'],['/admin/verifications','Verifications'],['/admin/activity','Activity'],['/admin/settings','Settings']];
const status=(x:string)=><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${['SUCCESS','VERIFIED','ACTIVE','RECORDED'].includes(x)?'bg-emerald-500/10 text-emerald-400':['FAILED','REVOKED','EXPIRED'].includes(x)?'bg-red-500/10 text-red-400':'bg-amber-500/10 text-amber-400'}`}>{x}</span>;
const Frame=({children}:{children:React.ReactNode})=><div className="overflow-x-auto rounded-2xl border border-card-border bg-card"><table className="w-full min-w-[700px] text-left text-sm">{children}</table></div>;
const Empty=({span,text}:{span:number;text:string})=><tr><td colSpan={span} className="p-10 text-center text-muted">{text}</td></tr>;

export const AdminDashboard=({user,loading}:Props)=>{const nav=useNavigate(),{pathname}=useLocation();const [data,setData]=useState<{overview:Overview;users:AdminUser[];packages:Pkg[];verifications:Verification[];activity:Audit[]}|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState<string|null>(null),[q,setQ]=useState(''),[filter,setFilter]=useState('ALL'); const label=links.find(x=>x[0]===pathname)?.[1]||'Overview';
 const load=async()=>{if(!user)return;setBusy(true);setError(null);try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw Error('Your session has expired. Please sign in again.');const h={Authorization:`Bearer ${session.access_token}`};const rs=await Promise.all(['/overview','/users','/packages','/verifications','/activity'].map(x=>fetch('/api/admin'+x,{headers:h})));const json=await Promise.all(rs.map(x=>x.json()));const bad=rs.findIndex(x=>!x.ok);if(bad>=0)throw Error(json[bad].error?.message||'Unable to load administration data.');setData({overview:json[0].data,users:json[1].data,packages:json[2].data,verifications:json[3].data,activity:json[4].data})}catch(e:any){setError(e.message||'Unable to load administration data.')}finally{setBusy(false)}};
 useEffect(()=>{if(!loading&&!user)nav('/login');else if(user)load()},[user,loading,nav]); const match=(...x:string[])=>x.join(' ').toLowerCase().includes(q.toLowerCase()); const controls=(options:string[])=><div className="mt-6 flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted"/><input className="field pl-9" value={q} onChange={e=>setQ(e.target.value)} placeholder={`Search ${label.toLowerCase()}…`}/></div><select className="field sm:w-48" value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">All statuses</option>{options.map(x=><option key={x}>{x}</option>)}</select></div>;
 if(loading||busy)return <div className="flex min-h-[50vh] items-center justify-center gap-3 text-muted"><Loader2 className="h-5 w-5 animate-spin text-primary"/>Loading administration data…</div>;if(error)return <div className="mx-auto mt-12 max-w-lg rounded-2xl border border-red-500/30 bg-red-950/30 p-6 text-center"><ShieldCheck className="mx-auto h-8 w-8 text-red-400"/><h1 className="mt-3 font-heading text-2xl font-bold text-white">Admin access unavailable</h1><p className="mt-2 text-sm text-muted">{error}</p><button onClick={load} className="mt-5 rounded-lg border border-card-border px-4 py-2 text-sm text-white">Try again</button></div>;if(!data)return null;
 const users=data.users.filter(x=>match(x.name,x.email,x.role)&&(filter==='ALL'||x.role===filter)),packages=data.packages.filter(x=>match(x.title,x.sender,x.status,x.verificationStatus)&&(filter==='ALL'||x.status===filter||x.verificationStatus===filter)),verifications=data.verifications.filter(x=>match(x.document,x.sender,x.method,x.status,x.result)&&(filter==='ALL'||x.status===filter)),audits=data.activity.filter(x=>match(x.user,x.action,x.resource));
 const UserTable=({rows}:{rows:AdminUser[]})=><Frame><thead className="bg-background/60 text-xs uppercase text-muted"><tr><th className="p-4">User</th><th>Email</th><th>Role</th><th>Registered</th></tr></thead><tbody>{rows.length?rows.map(x=><tr className="border-t border-card-border" key={x.id}><td className="p-4 text-white">{x.name||'—'}</td><td className="text-muted">{x.email}</td><td>{status(x.role)}</td><td className="text-muted">{new Date(x.createdAt).toLocaleDateString()}</td></tr>):<Empty span={4} text="No users match the selected filters."/>}</tbody></Frame>;
 const PackageTable=({rows}:{rows:Pkg[]})=><Frame><thead className="bg-background/60 text-xs uppercase text-muted"><tr><th className="p-4">Document package</th><th>Owner</th><th>Files / downloads</th><th>Uploaded</th><th>Verification</th><th>Status</th></tr></thead><tbody>{rows.length?rows.map(x=><tr className="border-t border-card-border" key={x.id}><td className="p-4"><p className="text-white">{x.title}</p><p className="text-xs text-muted">Expires {new Date(x.expiresAt).toLocaleString()}</p></td><td className="text-muted">{x.sender}</td><td className="text-muted">{x.fileCount} / {x.downloadCount}</td><td className="text-muted">{new Date(x.createdAt).toLocaleDateString()}</td><td>{status(x.verificationStatus)}</td><td>{status(x.status)}</td></tr>):<Empty span={6} text="No document packages match the selected filters."/>}</tbody></Frame>;
 let page:React.ReactNode=<><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[['Registered users',data.overview.statistics.totalUsers,Users],['Uploaded documents',data.overview.statistics.totalDocuments,FileStack],['Verified packages',data.overview.statistics.verifiedPackages,ShieldCheck],['Pending packages',data.overview.statistics.pendingPackages,Activity],['Failed verifications',data.overview.statistics.failedVerifications,ShieldCheck]].map(([l,v,Icon]:any)=><div className="rounded-2xl border border-card-border bg-card p-5" key={l}><Icon className="h-5 w-5 text-primary"/><p className="mt-5 font-heading text-3xl font-bold text-white">{v}</p><p className="text-sm text-muted">{l}</p></div>)}</section><div className="mt-8 grid gap-6 lg:grid-cols-2"><div><h2 className="mb-3 font-heading text-lg text-white">Recent uploads</h2><PackageTable rows={data.packages.slice(0,5)}/></div><div className="rounded-2xl border border-card-border bg-card p-5"><h2 className="font-heading text-lg text-white">Recent activity</h2><div className="mt-3 divide-y divide-card-border">{data.overview.activity.length?data.overview.activity.map(x=><div className="py-3" key={x.id}><p className="text-sm text-slate-200">{x.description}</p><p className="text-xs text-muted">{x.actor} · {new Date(x.createdAt).toLocaleString()}</p></div>):<p className="text-sm text-muted">No activity recorded yet.</p>}</div></div></div><h2 className="mb-3 mt-8 font-heading text-lg text-white">Recent users</h2><UserTable rows={data.users.slice(0,5)}/></>;
 if(pathname==='/admin/users')page=<>{controls(['ADMIN','SENDER','USER'])}<div className="mt-5"><UserTable rows={users}/></div></>;
 if(pathname==='/admin/documents')page=<><p className="text-sm text-muted">Metadata only; file access remains controlled by the existing secure package workflow.</p>{controls(['ACTIVE','REVOKED','EXPIRED','VERIFIED','PENDING'])}<div className="mt-5"><PackageTable rows={packages}/></div></>;
 if(pathname==='/admin/verifications')page=<>{controls(['SUCCESS','FAILED'])}<div className="mt-5"><Frame><thead className="bg-background/60 text-xs uppercase text-muted"><tr><th className="p-4">Document</th><th>Sender</th><th>Method</th><th>Result</th><th>Time</th></tr></thead><tbody>{verifications.length?verifications.map(x=><tr className="border-t border-card-border" key={x.id}><td className="p-4 text-white">{x.document}</td><td className="text-muted">{x.sender}</td><td className="text-muted">{x.method}</td><td>{status(x.status)}<p className="mt-1 text-xs text-muted">{x.result}</p></td><td className="text-muted">{new Date(x.createdAt).toLocaleString()}</td></tr>):<Empty span={5} text="No verification records match the selected filters."/>}</tbody></Frame></div></>;
 if(pathname==='/admin/activity')page=<><p className="text-sm text-muted">Security audit events from the existing audit log.</p>{controls([])}<div className="mt-5"><Frame><thead className="bg-background/60 text-xs uppercase text-muted"><tr><th className="p-4">User</th><th>Action</th><th>Resource</th><th>Status</th><th>Timestamp</th></tr></thead><tbody>{audits.length?audits.map(x=><tr className="border-t border-card-border" key={x.id}><td className="p-4 text-white">{x.user}</td><td>{x.action}</td><td className="text-muted">{x.resource}</td><td>{status(x.status)}</td><td className="text-muted">{new Date(x.createdAt).toLocaleString()}</td></tr>):<Empty span={5} text="No audit events are currently recorded."/>}</tbody></Frame></div></>;
 if(pathname==='/admin/settings')page=<div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-card-border bg-card p-6"><h2 className="font-heading text-lg text-white">Administrator account</h2><p className="mt-3 text-sm text-muted">{user?.email}</p><p className="mt-3 text-sm text-muted">Roles are securely controlled by Supabase Auth app metadata and cannot be changed from the browser.</p></div><div className="rounded-2xl border border-card-border bg-card p-6"><h2 className="font-heading text-lg text-white">Security configuration</h2><p className="mt-3 text-sm text-muted">Package expiry, PIN protection, storage, and verification use the existing backend configuration. No secrets are exposed here.</p></div></div>;
 return <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><div className="flex items-end justify-between gap-4"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-primary">Administration</p><h1 className="mt-2 font-heading text-3xl font-bold text-white">{label}</h1></div><button onClick={load} className="inline-flex h-10 items-center gap-2 rounded-lg border border-card-border px-4 text-sm text-white"><RefreshCw className="h-4 w-4"/>Refresh</button></div><nav className="mt-7 flex gap-2 overflow-x-auto border-b border-card-border pb-3">{links.map(([to,text])=><Link key={to} to={to} className={`whitespace-nowrap rounded-lg px-3 py-2 text-sm ${pathname===to?'bg-primary text-white':'text-muted hover:bg-card hover:text-white'}`}>{text}</Link>)}</nav><div className="mt-8">{page}</div></div>};
