import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { User } from '@supabase/supabase-js';
import { ArrowRight, ChevronDown, FileText, Loader2, Lock, QrCode, Search, ShieldCheck, Upload, Users } from 'lucide-react';
import { supabase } from '../lib/supabase';

export const PageHero = ({ eyebrow, title, copy, children }: { eyebrow: string; title: string; copy: string; children?: React.ReactNode }) => <section className="mx-auto max-w-5xl px-4 py-12 sm:py-20 text-center"><p className="font-mono text-xs font-semibold uppercase tracking-[.2em] text-primary">{eyebrow}</p><h1 className="mt-4 font-heading text-4xl font-bold tracking-tight text-white sm:text-6xl">{title}</h1><p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-muted">{copy}</p>{children}</section>;

const Card = ({ icon: Icon, title, children }: { icon: any; title: string; children: React.ReactNode }) => <article className="rounded-2xl border border-card-border bg-card p-6"><Icon className="h-6 w-6 text-primary" /><h2 className="mt-4 font-heading text-lg font-semibold text-white">{title}</h2><div className="mt-2 text-sm leading-6 text-muted">{children}</div></article>;

export const LandingPage = () => <><PageHero eyebrow="Secure document delivery" title="Share documents with proof, control, and confidence." copy="Digi-Doc creates temporary, protected document packages. Senders share a QR link or access code; recipients verify before they view or download."><div className="mt-8 flex flex-wrap justify-center gap-3"><Link to="/login" className="inline-flex h-11 items-center gap-2 rounded-lg bg-primary px-5 text-sm font-semibold text-white hover:bg-primary-hover">Get started <ArrowRight className="h-4 w-4" /></Link><Link to="/verify" className="inline-flex h-11 items-center gap-2 rounded-lg border border-card-border bg-card px-5 text-sm font-semibold text-white">Verify a document <QrCode className="h-4 w-4" /></Link></div></PageHero><section className="mx-auto grid max-w-6xl gap-4 px-4 pb-16 md:grid-cols-3"><Card icon={Lock} title="Private by design">Packages can be protected with a separate numeric PIN and expire automatically.</Card><Card icon={QrCode} title="Simple verification">A recipient scans a QR code or enters the supplied access code—no account required.</Card><Card icon={ShieldCheck} title="Secure delivery">Files are served through short-lived, authorized links instead of public storage paths.</Card></section></>;

export const HowItWorksPage = () => <><PageHero eyebrow="How Digi-Doc works" title="A safer route from sender to receiver." copy="The process stays straightforward on either side of the share." /><section className="mx-auto grid max-w-5xl gap-6 px-4 pb-16 md:grid-cols-2"><Card icon={Upload} title="For senders"><ol className="list-decimal space-y-2 pl-5"><li>Create a package and select its expiry.</li><li>Upload one or more supported files.</li><li>Optionally set a package PIN.</li><li>Share its QR link or access code.</li></ol></Card><Card icon={QrCode} title="For receivers"><ol className="list-decimal space-y-2 pl-5"><li>Scan the QR code or open the verification page.</li><li>Enter the access code supplied by the sender.</li><li>Enter the package PIN when required.</li><li>Review, preview, and download authorized files.</li></ol></Card></section></>;
export const AboutPage = () => <PageHero eyebrow="About Digi-Doc" title="Digital delivery that respects control." copy="Digi-Doc tackles the risk of sending important files through permanent or open links. Its package model combines access codes, optional PIN protection, expiry, verification events, and secure storage links. Built as a focused project for safer everyday document exchange." />;

const faqs = [['Getting started', 'How do I share a document?', 'Sign in, create a package, upload files, then share the QR link or access code.'], ['Verification', 'Do recipients need an account?', 'No. A recipient can verify a package with the access code and, if enabled, its PIN.'], ['QR codes', 'What does the QR code contain?', 'It contains the package retrieval link, not a storage bucket path.'], ['Security', 'Is an access code my password?', 'No. It is a separate package identifier. A package PIN is also distinct from your account authentication.'], ['Expiry', 'What happens after expiry?', 'The package can no longer be retrieved or downloaded.'], ['Accounts', 'How do I sign in?', 'This installation uses its configured Google authentication flow.']];
export const FaqPage = () => <><PageHero eyebrow="Support" title="Frequently asked questions" copy="Answers to common sharing, verification, and security questions." /><section className="mx-auto max-w-3xl space-y-3 px-4 pb-16">{faqs.map(([category, question, answer]) => <details key={question} className="group rounded-xl border border-card-border bg-card p-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-medium text-white"><span><span className="mr-3 text-xs uppercase tracking-wider text-primary">{category}</span>{question}</span><ChevronDown className="h-4 w-4 transition-transform group-open:rotate-180" /></summary><p className="mt-3 pr-8 text-sm leading-6 text-muted">{answer}</p></details>)}</section></>;
export const ContactPage = () => { const [sent,setSent]=useState(false); const submit=(e:FormEvent)=>{e.preventDefault();setSent(true)}; return <><PageHero eyebrow="Contact" title="Need help with a package?" copy="Send support a concise description. This deployment does not expose a support-ticket API, so this form confirms your message locally without claiming it was delivered."/><form onSubmit={submit} className="mx-auto max-w-xl space-y-4 px-4 pb-16"><select className="field" required><option value="">Choose an issue category</option><option>Access or verification</option><option>Upload or download</option><option>Account</option><option>Other</option></select><textarea required className="field min-h-36" placeholder="Tell us what happened and include the access code only if appropriate." />{sent && <p className="rounded-lg border border-amber-500/30 bg-amber-500/10 p-3 text-sm text-amber-300">Message captured in this session. Connect a support endpoint or mailbox to deliver it.</p>}<button className="h-11 rounded-lg bg-primary px-5 text-sm font-semibold text-white">Submit support request</button></form></> };
export const LegalPage = ({ terms=false }: {terms?:boolean}) => <><PageHero eyebrow="Legal" title={terms ? 'Terms & conditions' : 'Privacy policy'} copy={terms ? 'The rules for responsible use of Digi-Doc.' : 'How this application handles package and account information.'}/><article className="prose prose-invert mx-auto max-w-3xl px-4 pb-16 prose-p:text-muted prose-li:text-muted"><h2>{terms ? 'Using the service' : 'Information and documents'}</h2><p>{terms ? 'You are responsible for the files you upload, the people you share with, and keeping your account access secure. Do not use the service for unlawful, harmful, or unauthorized sharing.' : 'Digi-Doc uses authentication information to create your account session and package information to provide secure sharing. Uploaded files are stored through the configured secure storage integration.'}</p><h2>{terms ? 'Verification limitations' : 'Verification and storage'}</h2><p>{terms ? 'A successful package verification establishes that the supplied access information reached an active Digi-Doc package. It does not independently guarantee the accuracy, origin, or legal validity of a file.' : 'Access codes, optional package PINs, expiry rules, and short-lived file links are used to limit access. Retention and deletion follow the package lifecycle and configured backend behavior.'}</p><h2>{terms ? 'Availability' : 'Your choices'}</h2><p>{terms ? 'The service may be changed or unavailable during maintenance. No specific availability or legal guarantee is asserted by this interface.' : 'You may manage packages from your dashboard. For account or data requests, contact the project administrator using the available support route.'}</p></article></>;

type Pkg = { id:string; title:string; status:string; createdAt:string; expiresAt:string; accessCode:string; filesCount:number; downloadCount:number; hasPin:boolean };
const usePackages = (user:User|null) => { const [items,setItems]=useState<Pkg[]>([]); const [loading,setLoading]=useState(true); useEffect(()=>{if(!user){setLoading(false);return} ;(async()=>{try {const {data:{session}}=await supabase.auth.getSession(); const r=await fetch('/api/packages',{headers:{Authorization:`Bearer ${session?.access_token}`}}); const body=await r.json(); if(body.success)setItems(body.data)} finally {setLoading(false)}})()},[user]); return {items,loading}; };
export const DocumentsPage = ({user}:{user:User|null}) => { const {items,loading}=usePackages(user); const [q,setQ]=useState(''); const rows=useMemo(()=>items.filter(x=>x.title.toLowerCase().includes(q.toLowerCase())||x.accessCode.includes(q)),[items,q]); if(!user)return <AuthRequired/>; return <section className="mx-auto max-w-6xl px-4 py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Your workspace</p><h1 className="mt-3 font-heading text-3xl font-bold text-white">My documents</h1></div><Link to="/upload" className="inline-flex h-10 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-semibold text-white"><Upload className="h-4 w-4"/>Upload documents</Link></div><div className="relative mt-6"><Search className="absolute left-3 top-3 h-4 w-4 text-muted"/><input className="field pl-9" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search title or access code"/></div><div className="mt-5 overflow-x-auto rounded-2xl border border-card-border bg-card"><table className="w-full min-w-[650px] text-left text-sm"><thead className="text-xs uppercase text-muted"><tr><th className="p-4">Package</th><th>Files</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan={5} className="p-8 text-center text-muted">Loading documents…</td></tr>:rows.map(x=><tr className="border-t border-card-border" key={x.id}><td className="p-4"><p className="font-medium text-white">{x.title}</p><p className="font-mono text-xs text-primary">{x.accessCode}</p></td><td>{x.filesCount}</td><td><span className="text-xs text-muted">{x.status}</span></td><td className="text-muted">{new Date(x.createdAt).toLocaleDateString()}</td><td className="p-4"><Link className="text-primary" to={`/documents/${x.id}`}>Details</Link></td></tr>)}</tbody></table></div></section> };
export const DocumentDetailsPage=({user}:{user:User|null})=>{const {id}=useParams();const {items,loading}=usePackages(user);const pkg=items.find(x=>x.id===id);if(!user)return <AuthRequired/>;if(loading)return <Loading/>;if(!pkg)return <PageHero eyebrow="Documents" title="Package not found" copy="This package may no longer be available in your account."/>;return <section className="mx-auto max-w-3xl px-4 py-10"><Link className="text-sm text-primary" to="/documents">← My documents</Link><h1 className="mt-4 font-heading text-3xl font-bold text-white">{pkg.title}</h1><div className="mt-6 grid gap-4 sm:grid-cols-2"><Card icon={FileText} title="Package information"><p>Access code: <span className="font-mono text-primary">{pkg.accessCode}</span></p><p>Files: {pkg.filesCount}</p><p>Downloads: {pkg.downloadCount}</p></Card><Card icon={ShieldCheck} title="Sharing status"><p>{pkg.status}</p><p>Expires {new Date(pkg.expiresAt).toLocaleString()}</p><p>{pkg.hasPin?'PIN protection enabled.':'No package PIN.'}</p></Card></div><p className="mt-6 text-sm text-muted">Secure previews and downloads are available to recipients after verification, using the existing package share flow.</p><Link className="mt-5 inline-flex h-10 items-center rounded-lg bg-primary px-4 text-sm font-semibold text-white" to={`/share/${pkg.accessCode}`}>Open sharing view</Link></section>};
export const UploadPage=()=> <section className="mx-auto max-w-3xl px-4 py-14 text-center"><Upload className="mx-auto h-10 w-10 text-primary"/><h1 className="mt-4 font-heading text-3xl font-bold text-white">Upload a document package</h1><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-muted">Use the existing package creator to set the title, expiry, optional PIN, and upload supported file types securely.</p><Link to="/dashboard" className="mt-7 inline-flex h-11 items-center rounded-lg bg-primary px-5 text-sm font-semibold text-white">Create package</Link></section>;
export const ProfilePage=({user,onLogout}:{user:User|null;onLogout:()=>Promise<void>})=><section className="mx-auto max-w-2xl px-4 py-12"><h1 className="font-heading text-3xl font-bold text-white">Profile & settings</h1><div className="mt-6 rounded-2xl border border-card-border bg-card p-6"><Users className="h-6 w-6 text-primary"/><p className="mt-4 text-xs uppercase tracking-wider text-muted">Signed-in account</p><p className="mt-1 text-lg font-semibold text-white">{user?.user_metadata?.full_name || user?.email || 'No account session'}</p><p className="text-sm text-muted">{user?.email}</p><p className="mt-5 text-sm text-muted">Authentication is managed by the configured Supabase Google sign-in flow. Sensitive credentials are never shown here.</p><button onClick={()=>onLogout()} className="mt-6 h-10 rounded-lg border border-card-border px-4 text-sm font-semibold text-white">Log out</button></div></section>;
export const AuthCallback=()=>{const nav=useNavigate();useEffect(()=>{const t=setTimeout(()=>nav('/dashboard',{replace:true}),700);return()=>clearTimeout(t)},[nav]);return <section className="py-24"><Loading text="Completing secure sign-in…"/></section>};
export const ForgotPassword=()=> <PageHero eyebrow="Account access" title="Password reset is not available" copy="This Digi-Doc installation uses Google authentication. Reset your Google account password through Google, then return here to sign in."/>;
export const AuthRequired=()=> <PageHero eyebrow="Account required" title="Sign in to manage packages" copy="Use your configured Digi-Doc account to access this page."><Link to="/login" className="mt-6 inline-flex h-10 items-center rounded-lg bg-primary px-4 text-sm font-semibold text-white">Sign in</Link></PageHero>;
export const Loading=({text='Loading…'}:{text?:string})=><div className="flex items-center justify-center gap-2 p-12 text-sm text-muted"><Loader2 className="h-5 w-5 animate-spin text-primary"/>{text}</div>;
